Numpy indexing and selection Practice


In [1]:
import numpy as np

In [4]:
arr=np.arange(11)

In [5]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[8]

8

In [7]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

We can assign values or change values in array using slicing but we cant so this in list

Eg:
a=[1,2,3,4,5,6,7]
a[1:4]=100 giver error, but

a=np.array(a)
a[1:4]=100 is all ok.


In [9]:
arr[0:4]

array([0, 1, 2, 3])

In [11]:
arr[0:4]=100


In [13]:
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [15]:
a=np.arange(0,11)

In [16]:
slice=a[0:6]

In [17]:
slice

array([0, 1, 2, 3, 4, 5])

In [18]:
slice[:]

array([0, 1, 2, 3, 4, 5])

In [19]:
slice[:]=99

In [21]:
slice

array([99, 99, 99, 99, 99, 99])

In [22]:
a[:]

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])


Have you noticed, chaning the data in slice array, also changes the data in original array, so be careful regarding that. Numpy has created a refernce of array 'a' in array slice. To save the memory.

To make a copy instead of refernce, follow the step below.

In [23]:
copy_a=a.copy()

In [25]:
copy_a

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [26]:
a

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [27]:
copy_a[1:4]=100

In [28]:
copy_a

array([ 99, 100, 100, 100,  99,  99,   6,   7,   8,   9,  10])

In [29]:
a

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

See now the original aaray didt changed. only the copied array 'copy_a' values have changed.

__Matrix in numpy__

In [33]:
arr_2d=np.array([[5,10,15],[50,6,7],[35,40,45]])

In [34]:
arr_2d

array([[ 5, 10, 15],
       [50,  6,  7],
       [35, 40, 45]])

__Formats for grabing data from the matrix in numpy__

1- Double bracket format
2- Single bracket format

To grab 50 from the array

In [35]:
arr_2d[1][0]

50

Try to grab each element using double bracket.

now you can use single bracket using a ',' in the bracket

In [37]:
arr_2d[1,0]

50

We cant use single bracket format in list

In [38]:
arr_2d


array([[ 5, 10, 15],
       [50,  6,  7],
       [35, 40, 45]])

Suppose we have to grab [10,15],[6,7] only, then we can use single bracket format

In [41]:
arr_2d[:2,1:]

array([[10, 15],
       [ 6,  7]])

__Conditional selection__

In [44]:
arr=np.arange(0,11)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

We can compare the array using a conditional statement to get boolean values. 
Find all the values greater than 5.

In [46]:
bool_arr=arr>5

In [47]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True], dtype=bool)

To get all the values from arr whose values are true, just use 


In [48]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [49]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

Both are same

Find all the even numbers between 1-20

In [51]:
num=np.arange(1,21)
num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [52]:
even=num[num%2==0]

In [53]:
even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

__Exercise__
Create a 2d matirx from 1-50 and try to print [13,14],[23,24] using slicing

Solution

In [57]:
arr=np.arange(1,51).reshape(5,10)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [58]:
arr[1:3,2:4]

array([[13, 14],
       [23, 24]])